[phases.setup]
nixPkgs = ["ruby_3_2", "postgresql", "redis"]

[phases.install]
cmds = ["RAILS_ENV=production BUNDLE_WITHOUT='development:test' bundle install --deployment"]

[phases.build]
cmds = ["RAILS_ENV=production bundle exec rails db:migrate || true"]

[start]
cmd = "RAILS_ENV=production bundle exec rails server -b 0.0.0.0 -p $PORT"


