[phases.setup]
nixPkgs = ["ruby_3_2", "postgresql", "redis"]

[phases.install]
cmds = ["bundle config set --local without 'development test'", "bundle install"]

[phases.build]
cmds = ["bundle exec rails db:migrate || true"]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p $PORT"


